prf_dbt_project2_t1:
  outputs:
    dev:
      dbname: dbt_project2
      host: localhost
      pass: '12345678'
      port: 5432
      schema: project_2 #ini schema yang digunakan untuk load data
      threads: 1
      type: postgres
      user: dbtAdmin
  target: dev
